# Generated by Django 2.1 on 2018-08-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_auto_20180823_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.TextField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
