# Generated by Django 2.1 on 2018-08-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_remove_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.TextField(default='django', max_length=20),
            preserve_default=False,
        ),
    ]
